### PR TITLE
Update MAINTAINERS.md: Move people to Emeritus

### PR DESCRIPTION
**Pull request by ryjones**
mac-arrap's last activity was 2022-04-29

### CODE REVIEW

**Comment by brentzundel** [comment]
I think it makes sense to move Cam to the emeritus list.
@appetrosyan is it likely that @Erigara will be continuing as a maintainer of Ursa?

**Comment by appetrosyan** [comment]
Yes, as long as we’re developing Iroha

**Comment by ryjones** [comment]
@brentzundel @appetrosyan updated

**Review by mikelodder7 — APPROVED** [review]

**Comment by mikelodder7** [comment]
We should also remove others but that can be a separate PR.

**Review by brentzundel — APPROVED** [review]

**Pull request merged**
