### PR TITLE
CWE-325: Missing Required Cryptographic Step.

### PR DESCRIPTION
**Pull request by EvertonMelo**
indy-crypto-deps.zip 
hash: f2bcfe3523201d836e6c3cdaf8189aebf1a68a19

Description

The software does not implement a required step in a cryptographic algorithm, resulting in weaker encryption than advertised by that algorithm.
Context

The Phase identifies a point in the software life cycle at which introduction may occur, while the Note provides a typical scenario related to introduction during the given phase.

### CODE REVIEW

**Comment by mikelodder7** [comment]
This looks fine. Once you fix the DCO I can merge it. See the steps for fixing it [here](https://github.com/hyperledger/ursa/pull/5/checks)

**Comment by dhuseby** [comment]
+1

Thanks for updating the docs.  In the future I'd like to see us use a more robust file integrity mechanism.  Something like [minisign](https://jedisct1.github.io/minisign/) or the OpenBSD signify tool.

**Comment by hartm** [comment]
This is, in general, a good change.  But why is the checksum using a SHA-1 hash instead of a more modern (and less broken) hash function?

And +1 to Dave.  We will need a more robust tool in the long run.

**Comment by mikelodder7** [comment]
No longer applicable.

**Pull request closed without merging**
