### PR TITLE
add pairings library

### PR DESCRIPTION
**Pull request by mikelodder7**
Add pairings library which brings `pairing-plus` up to date with newer RustCrypto crates and fixes the hash-to-curve implementation to match the latest IETF spec.

The reason to bring it in here is due to the original repo not accepting the PR to update their repo and failure to maintain the repo. Luckily, there isn't much that is going to change with this so we passively maintain this library for Ursa's other primitives that depend on it.

### CODE REVIEW

**Comment by dcmiddle** [comment]
What do you think about forking that library and maintaining the patch in the fork? That seems to be the most common practice when I've looked into handling unmaintained dependencies. It preserves all of the existing boundaries and if the upstream project resumes maintenance then we can easily point back to it again.

**Comment by mikelodder7** [comment]
I’m fine with that

**Comment by hartm** [comment]
@dcmiddle , where should the fork live then?  Happy to defer to your open-source experience here.

**Comment by dcmiddle** [comment]
> @dcmiddle , where should the fork live then? Happy to defer to your open-source experience here.

Could live under mike's github account like mikelodder7/pairings or under HL like hyperledger/ursa-pairings.

**Comment by mikelodder7** [comment]
I’m happy to host it under my account

**Comment by mac-arrap** [comment]
@mikelodder7 should we close this PR or are we still needing this change in the code base?

**Comment by brentzundel** [comment]
This is a very old PR that has not seen any activity in months. 
If no opposition to doing so is raised in the next week, I am going to close this PR.

**Pull request closed without merging**
