### PR TITLE
Deb build

### PR DESCRIPTION
**Pull request by mikelodder7**
This PR enables ursa to build a debian package that can be installed on a Debian based OS

### CODE REVIEW

**Comment by dcmiddle** [comment]
```cargo-deb: Asset file path does not match any files: /Users/dcmiddle/project/ursa/libursa/../target/release/libursa.so```

Are you running this in an ubuntu container or right at your local command line?
```warning: This command is for Linux only, and will not make sense when run on other systems```

**Comment by mikelodder7** [comment]
Yes dan I am running in docker Ubuntu but it does work for me if I add a --target x86_64-unknown-linux-gnux32 it works but I had to install a cross compiler. Cargo deb doesn’t distinguish between the current system and what it actually builds. If you run it on OSX it compiles ursa for OSX and this the .so is not what is built. I can add your comments to the README if you think that helps

**Comment by dcmiddle** [comment]
> Yes dan I am running in docker Ubuntu but it does work for me if I add a --target x86_64-unknown-linux-gnux32 it works but I had to install a cross compiler. Cargo deb doesn’t distinguish between the current system and what it actually builds. If you run it on OSX it compiles ursa for OSX and this the .so is not what is built. I can add your comments to the README if you think that helps

Yeah that's probably helpful. Something like "on a debian OS run ...".
Is this something we should add to the travis script as well?

**Comment by mikelodder7** [comment]
> Yeah that's probably helpful. Something like "on a debian OS run ...".
> Is this something we should add to the travis script as well?

I thought about that but didn't think it really adds anything of value to the pipeline because it just builds Ursa then packages it. We are already testing the build portion and the packaging would just be testing the Cargo.toml stuff which should change much other than adding C include files. So I view this as mostly a redundant test if added to the CI.

**Pull request merged**
