### PR TITLE
add r1cs-select

### PR DESCRIPTION
**Pull request by mikelodder7**
This PR adds a command-line tool that demonstrates how to build an R1CS circuit frontend that can choose between multiple backends. This work was funded by research from Fujistu Labs and donated to Ursa per their request.

### CODE REVIEW

**Comment by dcmiddle** [comment]
Reflecting the discussion from the ursa community meeting...
This looks like a really interesting new feature - thanks for putting it together!
We would like to see an RFC or other discussion to help the community understand the structure and intents of the PR.
Please particularly include references or specs we can use the check the correctness of the implementation.
For large PRs like this, logically separable commits that can aid reviews along with descriptive commit messages (please see https://chris.beams.io/posts/git-commit/)

**Comment by dcmiddle** [comment]
The PR contains a number of commented sections. Please remove those or uncomment as appropriate.

**Comment by dcmiddle** [comment]
please add spdx license headers to each file
see https://wiki.hyperledger.org/display/TSC/Copyright+and+License+Policy
e.g. 
```// SPDX-License-Identifier: Apache-2.0```

**Comment by dcmiddle** [comment]
New features need unit and integration tests. Please ensure that you have good test coverage.
https://github.com/hyperledger/ursa/blob/main/CONTRIBUTING.md#the-commit-process

**Review by mac-arrap — APPROVED** [review]

**Review by mac-arrap — APPROVED** [review]
Everything here looks correct to me. I don't see any issues in the code

**Comment by brentzundel** [comment]
I remember looking at this back in September and thinking then that I would give a thorough review after @dcmiddle comments had been addressed. I don't see that that has happened just yet.

**Comment by brentzundel** [comment]
It has been over a year since changes were requested and since then no response has been made.
If no opposition to doing so is raised in the next week, I am going to close this PR.

**Pull request closed without merging**
