### PR TITLE
Migrate to k256

### PR DESCRIPTION
**Pull request by dcmiddle**
Separate commits for some namespace/dependency clarity and then the migration itself in its own commit.

### CODE REVIEW

**Comment by dcmiddle** [comment]
addresses https://github.com/hyperledger/ursa/issues/163

**Review by mikelodder7 — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Comment by hartm** [comment]
It looks like you guys are super on top of this.  Would you all like me to go over this too?

**Comment by dcmiddle** [comment]
> It looks like you guys are super on top of this. Would you all like me to go over this too?

**Comment by dcmiddle** [comment]
> It looks like you guys are super on top of this. Would you all like me to go over this too?

I'd rather not have to fix the things the other chaps let me get away with. But do as you see fit. ;)

**Comment by hartm** [comment]
"Chaps"?  I guess I'll have to respond with similar language.

I ain't always trust them other chaps, but seein' as you ain't touch them maths, them other chaps do a purty fine job o' gettin' it all right.  I took me an eyeball to your writin's, 'n they seem darn OK.  So as long as them test cases still run like a well oiled John Deere, I'm happier'n a pig 'n a sty to give you a +1.

**Review by hartm — APPROVED** [review]

**Pull request merged**
