### PR TITLE
Updated versions for k256 and p256 crates

### PR DESCRIPTION
**Pull request by Artemkaaas**
Updated versions for k256 and p256 crates in order to resolve dependency versions conflics with `ssi` crate

### CODE REVIEW

**Comment by dcmiddle** [comment]
thanks
why 0.8 version of each? It looks like latest is 0.9.

**Comment by Artemkaaas** [comment]
> thanks
> why 0.8 version of each? It looks like latest is 0.9.

The intention of changes I did was to resolve dependency conflicts with `ssi` crate we also use in our project. 
Furthermore, updating to `0.9` caused URSA compilation errors for me.

**Review by dcmiddle — APPROVED** [review]

**Comment by ryjones** [comment]
@Artemkaaas could you resolve the conflicts? It looks like main is up to 0.9.6

**Comment by Artemkaaas** [comment]
Closing this PR as libraries already was updated to the latest version in the PR: https://github.com/hyperledger/ursa/pull/188

**Pull request closed without merging**
