### PR TITLE
Add non-extended chacha20poly1305

### PR DESCRIPTION
**Pull request by andrewwhitehead**
Also updates chacha20poly1305 crate to 0.4.1

### CODE REVIEW

**Comment by mikelodder7** [comment]
@andrewwhitehead Thanks for this PR. Is there a compatibility reason or streaming reason for using chacha20poly1305? In most cases xchacha20poly1305 is preferred except in those two cases.

**Comment by andrewwhitehead** [comment]
@mikelodder7 Yes, it's for compatibility with the current Indy pack/unpack, which advertises xchacha but doesn't actually use it.

**Comment by kdenhartog** [comment]
> 
> 
> @mikelodder7 Yes, it's for compatibility with the current Indy pack/unpack, which advertises xchacha but doesn't actually use it.

Yeahhhhh.... Sorry bout that headache. Maybe we can make it consistent eventually?

**Comment by andrewwhitehead** [comment]
@kdenhartog  Because the nonce is detached, it would be pretty easy to support both by checking its length first (12 or 24 bytes).

**Comment by andrewwhitehead** [comment]
Also the updated pack/unpack exists here now:
https://github.com/bcgov/indy-shared-rs/blob/master/indy-utils/src/pack/alg.rs

It uses the crypto_box crate to create/open the nacl crypto box, and implements the sealed box manually.

**Comment by kdenhartog** [comment]
> @kdenhartog Because the nonce is detached, it would be pretty easy to support both by checking its length first (12 or 24 bytes).

We could just add support for both rather than relying on the implementation supporting only xchacha as well. I think it would be good to not indicate the wrong type of algorithm being used in the headers if it's possible to get everyone doing that.

**Pull request merged**
