### PR TITLE
Update default branch to main

### PR DESCRIPTION
**Pull request by ryjones**
Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by ryjones** [comment]
Don't just merge this - let me know when you're ready to merge, and I'll rename the branch

**Comment by dcmiddle** [comment]
We have a project meeting tomorrow (2021-02-03). That would be a good time to get everyone on the same page and if possible, merge any outstanding PRs against master.

**Comment by ryjones** [comment]
@dcmiddle outstanding PRs are automatically updated to the new branch.

**Comment by dcmiddle** [comment]
oh that’s slick

**Review by dcmiddle — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Pull request merged**
