### PR TITLE
Update +sudo labels README.md

### PR DESCRIPTION
**Pull request by EvertonMelo**
add parms SUDOrs and adjusted name for Ubuntu 16.04 LTS.

### CODE REVIEW

**Comment by EvertonMelo** [comment]
please confirm the way to iterate with the repository, whether it will be through Github (mirror) or https://gerrit.hyperledger.org/

**Comment by mikelodder7** [comment]
The way to iterate is definitely through GitHub. I can accept this PR once you apply your DCO.
It should be easy to do `git commit --amend --signoff`

**Comment by dhuseby** [comment]
+1

**Comment by mikelodder7** [comment]
Out of date now and no longer applicable

**Pull request closed without merging**
