### PR TITLE
Update Time crate

### PR DESCRIPTION
**Pull request by dcmiddle**
Fixes https://github.com/hyperledger/ursa/issues/196

### CODE REVIEW

**Comment by brentzundel** [comment]
looks like the build failed

**Review by danintel — APPROVED** [review]

**Comment by dcmiddle** [comment]
Build is failing because I missed an instance of `time`.
`libsodium-ffi` depends on `zip` depends on the old version of `time`. 
This is the latest version of `zip`.
Anyone know how to address this?

**Comment by hartm** [comment]
This might be a more complicated fix.

It seems like libsodium-ffi hasn't been updated in a while.  I'm not sure what the best libsodium wrapper for rust is at this point, either.

**Comment by brentzundel** [comment]
Would this one work? https://github.com/RustCrypto/nacl-compat

**Comment by brentzundel** [comment]
there are also many resources here that have been compiled by the rust crypto interest group:https://cryptography.rs/, in particular https://github.com/brndnmtthws/dryoc might work for us.

**Comment by dcmiddle** [comment]
blocked on https://github.com/zip-rs/zip/pull/254
Note libsodium-ffi is pegged to v0.5 of zip.
https://github.com/zonyitoo/libsodium-ffi/blob/master/Cargo.toml#L20
presumably the zip fix comes in with a point release on 0.5.

**Comment by andrewwhitehead** [comment]
It looks like libsodium-ffi is only used to check the validity of ed25519 and chacha20, and to provide an alternative backend for chacha20 encryption. I would suggest just removing it.

**Comment by hartm** [comment]
We discussed this issue in yesterday's Ursa meeting.  As @andrewwhitehead suggests, the best solution seems to be removing libsodium.  Other people in cryptography that I've discussed this with have also recommended that we ditch libsodium.  @mac-arrap

**Comment by andrewwhitehead** [comment]
Is this being worked on?

**Comment by dcmiddle** [comment]
@andrewwhitehead I was going to dig in later .. maybe tomorrow, but if you already know what needs to be excised feel free to go for it! lemme know.

**Comment by hartm** [comment]
Cam @mac-arrap said he was going to look at it.  You should feel free to take a peek yourself, but it would be great if you could include him as well.  Obviously, the more the merrier!

**Comment by dcmiddle** [comment]
superseded by https://github.com/hyperledger/ursa/pull/200

**Pull request closed without merging**
